---
kind: pipeline
type: exec
name: build-docker

clone:
  depth: 1

steps:
  - name: build_docker_image
    commands:
      - docker build -t zyra/gobac -t harbor.zyra.ca/zyra/gobac .

  - name: push_docker_image
    depends_on:
      - build_docker_image
    when:
      branch:
        - master
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_TOKEN:
        from_secret: DOCKER_TOKEN
    commands:
      - docker login harbor.zyra.ca -u $DOCKER_USERNAME -p $DOCKER_TOKEN
      - docker push harbor.zyra.ca/zyra/gobac

---
kind: pipeline
type: docker
name: build-binaries

clone:
  depth: 1

volumes:
  - name: gobac_binary_build_cache
    host:
      path: /tmp/gobac_binary_build_cache
  - name: shared_cache
    temp: {}

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: shared_cache
        path: /cache-dir
      - name: gobac_binary_build_cache
        path: /cache
    settings:
      restore: true
      mount:
        - cache-dir

  - name: linux-amd64
    image: golang:1.12-alpine
    volumes:
      - name: shared_cache
        path: /root/.cache
    depends_on:
      - restore-cache
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      -  go build -mod vendor -o gobac-linux-amd64 cmd/gobac/main.go

  - name: linux-arm64
    image: golang:1.12-alpine
    volumes:
      - name: shared_cache
        path: /root/.cache
    depends_on:
      - restore-cache
    environment:
      GOOS: linux
      GOARCH: arm64
    commands:
      -  go build -mod vendor -o gobac-linux-arm64 cmd/gobac/main.go

  - name: linux-arm
    image: golang:1.12-alpine
    depends_on:
      - restore-cache
    volumes:
      - name: shared_cache
        path: /root/.cache
    environment:
      GOOS: linux
      GOARCH: arm
    commands:
      - go build -mod vendor -o gobac-linux-arm cmd/gobac/main.go

  - name: windows-amd64
    image: golang:1.12-alpine
    depends_on:
      - restore-cache
    volumes:
      - name: shared_cache
        path: /root/.cache
    environment:
      GOOS: windows
      GOARCH: amd64
    commands:
      - go build -mod vendor -o gobac-windows-amd64 cmd/gobac/main.go

  - name: darwin-amd64
    image: golang:1.12-alpine
    depends_on:
      - restore-cache
    volumes:
      - name: shared_cache
        path: /root/.cache
    environment:
      GOOS: darwin
      GOARCH: amd64
    commands:
      - go build -mod vendor -o gobac-darwin-amd64 cmd/gobac/main.go

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on:
      - linux-amd64
      - linux-arm64
      - linux-arm
      - windows-amd64
      - darwin-amd64
    volumes:
      - name: shared_cache
        path: /cache-dir
      - name: gobac_binary_build_cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - cache-dir

---
kind: pipeline
name: after
depends_on:
  - build-docker
  - build-binaries
clone:
  disable: true
steps:
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: test-zone
      username: drone
    when:
      status: [ success, failure ]