format_version: 3
pipelines:
  gobac:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: git@github.com:zyra/gobac.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                - -o
                - mod
                - vendor
                - -o
                - gobac
                - cmd/gobac/main.go
                command: go
                run_if: passed
